### PR TITLE
Don't panic when min == max

### PR DESCRIPTION
**Pull request by vladimir-ch**
and fix some typos.

### CODE REVIEW

**Comment by btracey** [comment]
Personally I prefer the panic. Having min > max is more likely to be a bug than just someone not caring about the integrand bounds.

**Comment by vladimir-ch** [comment]
Another point of view is that both min==max and min>max are well defined, so why panic. I understand you point though, so I'll reverse the min>max case. I'll keep the min==max case, it is a corner case but returning 0 is much more natural than panicking.

**Comment by vladimir-ch** [comment]
PTAL @btracey

**Comment by btracey** [comment]
LGTM

**Pull request merged**
